### ISSUE TITLE
AttributeError: 'set' object has no attribute 'extend'

### ISSUE THREAD

**Issue by jan-matejka** [containers/podman-compose#1507]
```Traceback (most recent call last):
  File "/home/alex/.local/venv/podman-compose-1.6.0/bin/podman-compose", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/alex/git/3rd/podman-compose/main/podman_compose.py", line 4972, in main
    asyncio.run(async_main())
    ~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/alex/git/3rd/podman-compose/main/podman_compose.py", line 4967, in async_main
    await podman_compose.run()
  File "/home/alex/git/3rd/podman-compose/main/podman_compose.py", line 2373, in run
    self._parse_compose_file()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/alex/git/3rd/podman-compose/main/podman_compose.py", line 2685, in _parse_compose_file
    resolve_extends(services, [name for _, name in service_names], self.environ)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/git/3rd/podman-compose/main/podman_compose.py", line 2246, in resolve_extends
    new_service = rec_merge({}, from_service, service)
  File "/home/alex/git/3rd/podman-compose/main/podman_compose.py", line 2198, in rec_merge
    ret = rec_merge_one(target, source)
  File "/home/alex/git/3rd/podman-compose/main/podman_compose.py", line 2181, in rec_merge_one
    value.extend(value2)
    ^^^^^^^^^^^^
AttributeError: 'set' object has no attribute 'extend'
```

The value2 is ```{<podman_compose.ServiceDependency object at 0x7fb276394f50>}```

I'm unable to produce sscce for compose.yaml at this time.
pc version 1.5.0 works with the same compose.yaml.

```% pc --version
podman-compose version 1.6.0
podman version 5.4.2
```

**Environment:**
 - OS: Linux

**Comment by jan-matejka** [comment]
Introduced by 4aa11de6bf2a7d12bb4496eb9e7de6e396d046d9
Reverting the commit seems to fix the issue, at least as far as `pc config` is concerned.

**Comment by arbelonson-source** [comment]
Traced this — happy to open a PR if you're okay with it. Disclosure up front: I run agent loops (Claude Code) that find and fix issues like this, so this diagnosis and fix are AI-produced, not something I personally read the code for. Asking before opening a PR rather than doing it unprompted.

**What commit 4aa11de6 was actually for**: it made `podman-compose down app` not stop `app`'s upstream dependencies. To do that it added a new `calc_dependents()` step that computes, for every service, the set of *other* services that depend on it (`_dependents`), stored the same way the existing `_deps` field already is (a `set[ServiceDependency]`).

**Root cause of this bug**: `rec_merge_one`'s `is_list()` check returns `True` for a `set` too — it only excludes `str` and `dict` — so when both sides of a merge already have a `_deps` or `_dependents` set (both are internal bookkeeping fields populated by `flat_deps`, which runs before `resolve_extends`), the merge falls into the list branch and crashes on `value.extend(value2)`, since `set` has no `.extend()`.

`resolve_extends` already deletes `_deps` from the base service before merging, specifically to avoid this — but that cleanup was written before `_dependents` existed and was never extended to cover it too. So the crash only shows up when both the service being extended *and* the extending service are each depended on by some other service (which is why your `compose.yaml` — using both `extends` and `depends_on` together — hits it and a simpler one wouldn't).

**Fix**: rather than special-casing every internal field name that happens to hold a set, I made the merge itself handle sets correctly — union them via `.update()` instead of falling into the list branch. This isn't a revert of 4aa11de6; the dependents-tracking behavior it added still works, it's just merged correctly now when it collides with `extends`.

**Verified**:
- Reproduced the exact reported traceback end-to-end via `podman-compose config` on unmodified `main`, using a `base`/`derived` (`extends`) pair where a third and fourth service each `depends_on` one of them — confirmed it's still live today, not stale.
- Fixed version produces correct, complete config output for the same file.
- Added `tests/unit/test_rec_merge_set_values.py`, confirmed both new tests fail with the exact reported `AttributeError` on unmodified `main` and pass with the fix.
- Full existing suite: `python -m pytest tests/unit/` → 480 passed. `ruff check` and `ruff format --check` both clean.

Diff, if useful before a PR exists: https://github.com/containers/podman-compose/compare/main...arbelonson-source:podman-compose:fix/1507-set-extend-attributeerror
